add_newline = true

[character]
success_symbol = "[Î»](bold green) "
error_symbol = "[Î»](bold red) "
vicmd_symbol = "[V](bold green) "

[julia]
symbol = "âˆ´ "

[rust]
format = "via [âš™ï¸ $version](red bold)"

[git_status]
conflicted = "ğŸ³"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"
